import 'package:get/get_navigation/src/root/internacionalization.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      "app_name": "Sneho App",
      "profile": "Profile",
      "support_help": "Support & Help",
      "language": "Language",
      "continue": "Continue",
      "login": "Login",
      "sign_up": "Sign Up",
      "email": "Email",
      "password": "Password",
      "confirm_password": "Confirm Password",
      "forgot_password": "Forgot Password?",
      "dont_have_account": "Don't have an account?",
      "already_have_account": "Already have an account?",
      "home": "Home",
      "settings": "Settings",
      "logout": "Logout",
      "save": "Save",
      "cancel": "Cancel",
      "submit": "Submit",
      "loading": "Loading...",
      "error": "Error",
      "success": "Success",
      "edit_profile": "Edit Profile",
      "my_payments": "My Payments",
      "security": "Security",
      "change_password": "Change Password",
      "about_us": "About Us",
      "privacy_policy": "Privacy Policy",
      "terms_conditions": "Terms & Conditions",
      "contact_us": "Contact Us",
      "rate_app": "Rate App",
      "share_app": "Share App",
      "get_started": "Get Started",
      "location": "Location",
      "onboarding_title_1":
          "Providing expert care, personalized guidance, and unwavering support for every stage — planning, pregnancy, and parenting.",
      "onboarding_title_2":
          "Get daily tips, health tracking, and guidance from trusted sources, tailored to your stage of parenthood.",
      "onboarding_title_3":
          "Easily book appointments and have real-time conversations with trusted healthcare professionals — all from the comfort of your home.",
      "expert_advice": "Expert Advice",
      "next": "Next",
      "contact_number_required": "Contact number is required",
      "invalid_phone_number": "Please enter a valid phone number",
      "password_required": "Password is required",
      "password_min_length": "Password must be at least 6 characters",
      "please_accept_terms": "Please accept terms and conditions",
      "login_successful": "Login successful",
      "invalid_credentials": "Invalid phone number or password",
      "server_error": "Server error, please try again later",
      "network_error": "Network error, please check your connection",
      "something_went_wrong": "Something went wrong, please try again",
      "connect_doctors": "Connect Doctors",
      "lets_go": "Lets Go...",
      "setup_your_pregnancy_profile": "Setup Your Pregnancy Profile",
      "create_your_unique_profile": "Create Your Unique and Memorable Profile",
      "personal_information": "Personal Information",
      "full_name": "Full Name",
      "enter_your_full_name": "Enter Your Full Name",
      "date_of_birth": "Date of Birth",
      "select_date_of_birth": "Select Date of Birth",
      "contact_number": "Contact Number",
      "enter_your_contact_number": "Enter Your Contact Number",
      "blood_group": "Blood Group",
      "select_blood_group": "Select Blood Group",
      "email_address_optional": "Email Address (Optional)",
      "enter_your_email": "Enter Your Email",
      "location_city_district": "Location (City/District)",
      "enter_your_city_district": "Enter Your City/District",
      "pregnancy_information": "Pregnancy Information",
      "last_menstrual_period_date": "Last Menstrual Period (LMP) Date",
      "select_lmp_date": "Select LMP Date",
      "expected_due_date": "Expected Due Date",
      "auto_calculated": "Auto-calculated",
      "pregnancy_week": "Pregnancy Week",
      "number_of_pregnancies_optional": "Number of Pregnancies (Optional)",
      "enter_number_of_pregnancies": "Enter number of pregnancies",
      "physical_information": "Physical Information",
      "height_ft": "Height (ft)",
      "height": "Height",
      "weight_kg": "Weight (kg)",
      "weight": "Weight",
      "select_role": "Select Role",
      "choose_your_specific_role": "Choose Your Specific Role",
      "planning_to_conceive": "Planning to Conceive",
      "pregnancy": "Pregnancy",
      "parents": "Parents",
      "doctor_consultation_only": "Doctor Consultation Only",
      "setup_your_conceive_profile": "Setup Your Conceive Profile",
      "expert_tips": "Expert Tips",
      "doctors": "Doctors",
      "tools": "Tools",
      "customer_support": "Customer Support",
      "about_sneho": "About Sneho",
      "navigation": "Navigation",
      "navigating_to_baby_profile": "Navigating to Baby Profile",
      "navigating_to_change_password": "Navigating to Change Password",
      "navigating_to_customer_support": "Navigating to Customer Support",
      "navigating_to_privacy_policy": "Navigating to Privacy Policy",
      "navigating_to_about_sneho": "Navigating to About Sneho",
      "are_you_sure_logout": "Are you sure you want to logout?",
      "logged_out_successfully": "Logged out successfully",
      "edit": "Edit",
      "edit_profile_functionality": "Edit profile functionality",
      "edit_pregnancy_profile": "Edit Pregnancy Profile",
      "select_profile_photo": "Select Profile Photo",
      "camera": "Camera",
      "gallery": "Gallery",
      "update": "Update",
      "enter_your_height": "Enter Your Height",
      "enter_your_weight": "Enter Your Weight",

      "failed_to_pick_image": "Failed to pick image",
      "welcome_back": "Welcome back,",
      "3d_baby_visualization": "3d Baby Visualization",
      "baby_size_visualization": "Baby Size Visualization",
      "message": "Message",
      "comming_soon": "Comming soon",
      "todays_tips": "Today's Tips",
      "see_all": "See All",
      "baby_growth_tracker": "Baby Growth Tracker",
      "day": "Day",
      "baby_currently_size": "Baby currently the size of on ( Coconut )",
      "baby_weight": "Baby Weight",
      "delivery_date": "Delivery Date",
      "conception_information": "Conception Information",
      "trying_to_conceive_since": "Trying to conceive since",
      "select_conceive_date": "Select Date",
      "any_existing_health_conditions":
          "Any existing health conditions? (Optional)",
      "enter_health_conditions": "Enter health conditions if any",
      "full_name_required": "Full name is required",
      "full_name_min_length": "Full name must be at least 2 characters",
      "date_of_birth_required": "Date of birth is required",
      "must_be_18_years": "Must be at least 18 years old",
      "invalid_date_of_birth": "Please enter a valid date of birth",
      "select_gender_required": "Please select gender",

      "conceive_date_before_birth": "Conceive date cannot be before birth date",
      "location_required": "Location is required",

      "invalid_email": "Please enter a valid email",
      "height_required": "Height is required",
      "invalid_height": "Please enter a valid height (1-300 cm)",
      "weight_required": "Weight is required",
      "invalid_weight": "Please enter a valid weight (1-500 kg)",

      "profile_saved_successfully": "Profile saved successfully!",
      "profile_save_failed": "Failed to save profile",

      "period_days": "Period Days",
      "menstruation": "Menstruation",
      "ovulation": "Ovulation",
      "proliferative": "Proliferative",
      "secretory": "Secretory",

      "period_tracker": "Period Tracker",

      "end_cycle": "End Cycle",
      "ovulation_time": "Ovulation Time",
      "period_start": "Period Start",
      "new_cycle": "New Cycle",

      "sneho_expert_tips": "Sneho Expert Tips",
      "day_wish_tips": "Day Wish Tips",
      "no_tips_available_for_day": "No tips available for Day",

      "sneho_doctors": "Sneho Doctor's",
      "i_am_looking_for": "I am looking for",
      "doctors_available": "@count Doctor's Available",
      "gynecologist": "Gynecologist",
      "year_exp": "Year EXP",
      "available_now": "Available Now",
      "offline_now": "Offline Now",
      "video_call": "Video Call",
      "consultation_fee": "Consultation Fee",
      "instant_appointment": "Instant Appointment",
      "no_tips_available": "No tips available",

      // Doctor Details Screen
      "doctor_profile": "Doctor Profile",
      "experience": "Experience",
      "patients": "Patients",
      "biography": "Biography",
      "what_people_say": "What People Say",
      "review_on": "On",

      // Doctor Payment Screen
      "overview": "Overview",
      "patient_information": "Patient Information",
      "mobile_number": "Mobile Number",
      "patient_name": "Patient Name",
      "add_prescription_report": "Add prescription / Report",
      "consultation_type": "Consultation Type",
      "talk_to_doctor_video_call": "Talk to the doctor via video call",
      "book_appointment": "Book Appointment",
      "payment_details": "Payment Details",
      "promo_code": "Promo Code",
      "apply": "Apply",
      "vat_5_percent": "Vat (5%)",
      "platform_fee": "Platform Fee",
      "total_amount": "Total Amount",
      "payment_now": "Payment Now",

      // Tools Screen
      "sneho_tools": "Sneho Tools",
      "doctor_prescription": "Doctor Prescription",
      "doctor_appointment": "Doctor Appointment",

      // Doctor Appointment/Prescription Tool
      "upcoming": "Upcoming",
      "previous": "Previous",
      "view_appointment": "View Appointment",
      "view_prescription": "View Prescription",

      // Profile Screen
      "gender": "Gender",
      "select_gender": "Select Gender",
      "male": "Male",
      "female": "Female",
      "other": "Other",
      "email_address": "Email Address",
      "enter_your_location": "Enter Your Location",
      "update_profile": "Update Profile",
      "remove_image": "Remove Image",
      "profile_updated_successfully": "Profile updated successfully!",
      "profile_update_failed": "Failed to update profile",
      "loading_profile_data": "Loading profile data...",
      "account_login": "Account Login",
      "login_description":
          "Start your doctor appointment and medical consultation journey on the Sneho app",
      "phone_number": "Phone Number",
      "enter_phone_number": "Enter Phone Number",

      "enter_password": "Enter Password",
      "remember_me": "Remember me",
      "create_account": "Create An Account",
      "register_description":
          "Register and start doctor appointments and medical consultations on the Sneho app.",
      "name": "Name",
      "enter_name": "Enter Name",
      "sign_in": "Sign In",
      "aci_pure_products": "ACI Pure Products",
      "health_wellness": "Health & Wellness",
      "popular_specialists": "Popular Specialists",
      "view_all": "View All",
      "view_all_specialists": "View All Specialists",
      "medicine_specialist": "Medicine Specialist",
      "dermatology": "Dermatology",
      "years": "years",
      "child_information": "Child Information",
      "childs_name": "Child's Name",
      "enter_your_childs_name": "Enter Your Child's Name",
      "childs_birth_date": "Child's Birth Date",
      "select_childs_birth_date": "Select Child's Birth Date",
      "childs_gender": "Child's Gender",
      "childs_blood_group": "Child's Blood Group",
      "number_of_children": "Number of Children",
      "enter_number_of_children": "Enter Number of Children",

      "find_doctors_by_department": "Find Doctors by Department",
      "view_all_departments": "View All Departments",
      "select_clinical_areas":
          "Select from 30+ clinical areas to find a doctor",
      "instant_video_consultation": "Get Instant Video Consultation",
      "consultation_24_7": "Get consultation 24/7 within just 10 minutes",
      "experienced_mbbs_doctor": "Experienced MBBS Doctor",
      "experienced_child_doctor": "Experienced Child Doctor",
      "experienced_female_gyne": "Experienced Female Gyne",
      "treat_dengue_fever": "Treat Dengue Fever",
      "view_details": "View Details ",
      "setup_your_profile": "Setup Your Profile",
      "create_medical_profile": "Create Your Medical Consultation Profile",
      "medical_information": "Medical Information",
      "consultation_purpose": "Consultation Purpose / Medical Concern (brief)",
      "describe_medical_concern":
          "Describe your medical concern or reason for consultation",

      // Department names
      "general_physician": "General Physician",
      "pediatrics": "Pediatrics",
      "gynae_ops": "Gynae & Ops",
      "internal_medicine": "Internal Medicine",
      "endocrinology": "Endocrinology",
      "neurology": "Neurology",
      "gastroenterology": "Gastroenterology",
      "cardiology": "Cardiology",
      "urology": "Urology",
      "nutrition_food_science": "Nutrition & Food Science",
      "dentistry": "Dentistry",
      "month": "Month",
      "baby_age": "Baby Age",
      "days_left_to_turn_two": "Child has 304 days left to turn 2 years",
      "birthday": "Birthday",
      "child_name_required": "Child's name is required",
      "child_birth_date_required": "Child's birth date is required",

      "select_blood_group_required": "Please select child's blood group",
      "number_of_children_required": "Number of children is required",
      "min_children_required": "Number of children must be at least 1",
      "valid_number_required": "Please enter a valid number",
      "valid_height_required": "Please enter a valid height",
      "valid_weight_required": "Please enter a valid weight",
      "terms_confirmation":
          "By proceeding, you acknowledge that you are 18 years of age or older and that you agree to abide by our Terms of Service and Privacy Policy.",

      "Health_Support": "Health Support",
      "Emotional_Wellbeing": "Emotional Wellbeing",
      "Healthy_Lifestyle": "Healthy Lifestyle",
      "Nutrition_Guide": "Nutrition Guide",
      "Fertility_Awareness": "Fertility Awareness",
      'ovulating_now': 'Ovulating Now',
      'next_ovulation': 'Next Ovulation',
      "Parents_Self_Care": "Parents Self Care",
      "Childhood_Diseases_Care": "Childhood Diseases Care",
      "Sleep_Routine": "Sleep Routine",
      "Special_Baby_Care": "Special Baby Care",
      "patient_problem": "Patient Problem",
      "say_something": "Say Something",
      "please_enter_your_problem": "Please enter your problem",
      "describe_your_problem_in_at_least_5_characters":
          "Describe your problem in at least 5 characters",
      "Food_Nutrition": "Food & Nutrition",
      "Mothers_Health": "Mother's Health",
      "Mothers_Risks": "Mother's Risks",
      "Pregnancy_Mother_Care": "Pregnancy Care",
      "Mothers_Beauty": "Mother's Beauty",

      "how_can_we_help": "How Can We Help You?",
      "support_message":
          "We're here to assist you with any questions or concerns. Choose your preferred way to reach us.",
      "email_support": "Email Support",
      "phone_support": "Phone Support",
      "whatsapp_support": "WhatsApp Support",
      "chat_with_us": "Chat with us on WhatsApp",
      "faq": "Frequently Asked Questions",
      "office_hours": "Office Hours",
      "saturday_thursday": "Saturday - Thursday",
      "friday_closed": "Friday: Closed",
      "how_to_update_profile": "How do I update my profile?",
      "profile_update_answer":
          "Go to your profile, tap the edit icon, make changes, and save. Your information will be updated immediately.",
      "how_to_track_pregnancy": "How do I track my pregnancy?",
      "pregnancy_track_answer":
          "The app automatically tracks your pregnancy based on your LMP date. View your progress on the home screen.",
      "app_support_languages": "What languages does the app support?",
      "language_support_answer":
          "Sneho currently supports English and Bengali. You can switch languages from the profile screen.",

      // Privacy Policy Screen
      "last_updated": "Last Updated",
      "introduction": "Introduction",
      "information_we_collect": "Information We Collect",
      "how_we_use_info": "How We Use Your Information",
      "data_sharing": "Data Sharing & Disclosure",
      "data_security": "Data Security",
      "your_rights": "Your Rights",
      "data_retention": "Data Retention",
      "childrens_privacy": "Children's Privacy",
      "international_transfers": "International Data Transfers",
      "policy_changes": "Changes to This Policy",

      // About Sneho Screen
      "version": "Version",
      "sneho_tagline": "Your trusted companion for pregnancy & parenting",
      "our_mission": "Our Mission",
      "mission_description":
          "Sneho is dedicated to empowering mothers and families with reliable health information, expert guidance, and compassionate support throughout the pregnancy and parenting journey. We believe every mother deserves access to quality healthcare and personalized care.",
      "what_we_offer": "What We Offer",
      "pregnancy_tracking": "Pregnancy Tracking",
      "pregnancy_tracking_desc":
          "Monitor your pregnancy journey week by week with personalized insights",
      "health_tips": "Health Tips & Guidance",
      "health_tips_desc": "Daily expert tips tailored to your pregnancy stage",
      "expert_support": "Expert Support",
      "expert_support_desc":
          "Connect with qualified doctors and healthcare professionals",
      "multilingual": "Multilingual Support",
      "multilingual_desc":
          "Available in English and Bengali for better accessibility",
      "our_team": "Our Team",
      "team_description":
          "Sneho is built by a passionate team of healthcare professionals, developers, and parents who understand the challenges of pregnancy and parenting. We work tirelessly to provide you with the best possible experience.",
      "connect_with_us": "Connect With Us",
      "all_rights_reserved": "All Rights Reserved",
      "this_month_tips": "This Month's Tips",
      "baby_vaccine": "Baby Vaccine",
    },
    'bn_BD': {
      "app_name": "স্নেহ অ্যাপ",
      "profile": "প্রোফাইল",
      "support_help": "সহায়তা ও সাহায্য",
      "language": "ভাষা",
      "continue": "চালিয়ে যান",
      "login": "লগইন",
      "sign_up": "নিবন্ধন",
      "email": "ইমেইল",
      "password": "পাসওয়ার্ড",
      "confirm_password": "পাসওয়ার্ড নিশ্চিত করুন",
      "forgot_password": "পাসওয়ার্ড ভুলে গেছেন?",
      "dont_have_account": "অ্যাকাউন্ট নেই?",
      "already_have_account": "ইতিমধ্যে অ্যাকাউন্ট আছে?",
      "home": "হোম",
      "settings": "সেটিংস",
      "logout": "লগআউট",
      "save": "সংরক্ষণ",
      "cancel": "বাতিল",
      "submit": "জমা দিন",
      "loading": "লোড হচ্ছে...",
      "error": "ত্রুটি",
      "success": "সফল",
      "edit_profile": "প্রোফাইল সম্পাদনা",
      "my_payments": "আমার পেমেন্ট",
      "security": "নিরাপত্তা",
      "change_password": "পাসওয়ার্ড পরিবর্তন",
      "about_us": "আমাদের সম্পর্কে",
      "privacy_policy": "গোপনীয়তা নীতি",
      "terms_conditions": "শর্তাবলী",
      "contact_us": "যোগাযোগ করুন",
      "rate_app": "অ্যাপ রেট দিন",
      "share_app": "অ্যাপ শেয়ার করুন",
      "get_started": "শুরু করুন",
      "location": "লোকেশন",
      "onboarding_title_1":
          "পরিকল্পনা, গর্ভাবস্থা এবং অভিভাবকত্ব - প্রতিটি পর্যায়ে বিশেষজ্ঞ যত্ন, ব্যক্তিগতকৃত নির্দেশনা এবং অটল সহায়তা প্রদান",
      "onboarding_title_2":
          "আপনার পিতামাতার স্তরের সাথে মানানসই বিশ্বস্ত উৎস থেকে প্রতিদিনের টিপস, স্বাস্থ্য ট্র্যাকিং এবং নির্দেশনা পান।",
      "onboarding_title_3":
          "সহজেই অ্যাপয়েন্টমেন্ট বুক করুন এবং বিশ্বস্ত স্বাস্থ্যসেবা পেশাদারদের সাথে রিয়েল-টাইম কথোপকথন করুন — সবই আপনার বাড়ির আরাম থেকে।",
      "expert_advice": "বিশেষজ্ঞ পরামর্শ",
      "next": "পরবর্তী",
      "connect_doctors": "ডাক্তারদের সাথে সংযোগ",
      "lets_go": "চলুন শুরু করি...",
      "contact_number_required": "যোগাযোগ নম্বর প্রয়োজন",
      "invalid_phone_number": "দয়া করে একটি বৈধ ফোন নম্বর লিখুন",
      "password_required": "পাসওয়ার্ড প্রয়োজন",
      "password_min_length": "পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে",
      "please_accept_terms": "দয়া করে শর্তাবলী এবং গোপনীয়তা নীতি গ্রহণ করুন",
      "login_successful": "লগইন সফল হয়েছে",
      "invalid_credentials": "ভুল ফোন নম্বর বা পাসওয়ার্ড",
      "server_error": "সার্ভার ত্রুটি, পরে আবার চেষ্টা করুন",
      "network_error": "নেটওয়ার্ক ত্রুটি, আপনার সংযোগ পরীক্ষা করুন",
      "something_went_wrong": "কিছু সমস্যা হয়েছে, আবার চেষ্টা করুন",
      "select_role": "ভূমিকা নির্বাচন করুন",
      "choose_your_specific_role": "আপনার নির্দিষ্ট ভূমিকা নির্বাচন করুন",
      "planning_to_conceive": "গর্ভধারণের পরিকল্পনা",
      "pregnancy": "গর্ভাবস্থা",
      "parents": "পিতামাতা",
      "doctor_consultation_only": "শুধুমাত্র ডাক্তার পরামর্শ",
      "setup_your_pregnancy_profile": "আপনার গর্ভাবস্থা প্রোফাইল সেটআপ করুন",
      "create_your_unique_profile":
          "আপনার অনন্য এবং স্মরণীয় প্রোফাইল তৈরি করুন",
      "personal_information": "ব্যক্তিগত তথ্য",
      "full_name": "পুরো নাম",
      "enter_your_full_name": "আপনার পুরো নাম লিখুন",
      "date_of_birth": "জন্ম তারিখ",
      "select_date_of_birth": "জন্ম তারিখ নির্বাচন করুন",
      "contact_number": "যোগাযোগ নম্বর",
      "enter_your_contact_number": "আপনার যোগাযোগ নম্বর লিখুন",
      "blood_group": "ব্লাড গ্রুপ",
      "select_blood_group": "ব্লাড গ্রুপ নির্বাচন করুন",
      "email_address_optional": "ইমেইল ঠিকানা (ঐচ্ছিক)",
      "enter_your_email": "আপনার ইমেইল লিখুন",
      "location_city_district": "লোকেশন (শহর/জেলা)",
      "enter_your_city_district": "আপনার শহর/জেলা লিখুন",
      "pregnancy_information": "গর্ভাবস্থার তথ্য",
      "last_menstrual_period_date": "শেষ মাসিকের তারিখ",
      "select_lmp_date": "শেষ মাসিকের তারিখ নির্বাচন করুন",
      "expected_due_date": "প্রত্যাশিত প্রসব তারিখ",
      "auto_calculated": "স্বয়ংক্রিয়ভাবে গণনা করা",
      "pregnancy_week": "গর্ভাবস্থার সপ্তাহ",
      "number_of_pregnancies_optional": "গর্ভধারণের সংখ্যা (ঐচ্ছিক)",
      "enter_number_of_pregnancies": "গর্ভধারণের সংখ্যা লিখুন",
      "physical_information": "শারীরিক তথ্য",
      "height_ft": "উচ্চতা (ফুট)",
      "height": "উচ্চতা",
      "weight_kg": "ওজন (কেজি)",
      "weight": "ওজন",
      "expert_tips": "বিশেষজ্ঞ টিপস",
      "doctors": "ডাক্তাররা",
      "tools": "টুলস",
      "setup_your_conceive_profile": "আপনার গর্ভধারণের প্রোফাইল সেটআপ করুন",

      "customer_support": "গ্রাহক সহায়তা",

      "about_sneho": "স্নেহ সম্পর্কে",
      "navigation": "নেভিগেশন",
      "navigating_to_baby_profile": "বেবি প্রোফাইলে নেভিগেট করা হচ্ছে",
      "navigating_to_change_password": "পাসওয়ার্ড পরিবর্তনে নেভিগেট করা হচ্ছে",
      "navigating_to_customer_support": "গ্রাহক সহায়তায় নেভিগেট করা হচ্ছে",
      "navigating_to_privacy_policy": "গোপনীয়তা নীতিতে নেভিগেট করা হচ্ছে",
      "navigating_to_about_sneho": "স্নেহ সম্পর্কে নেভিগেট করা হচ্ছে",
      "are_you_sure_logout": "আপনি কি নিশ্চিত যে লগআউট করতে চান?",
      "logged_out_successfully": "সফলভাবে লগআউট হয়েছে",
      "edit": "সম্পাদনা",
      "edit_profile_functionality": "প্রোফাইল সম্পাদনা কার্যকারিতা",
      "edit_pregnancy_profile": "গর্ভাবস্থা প্রোফাইল সম্পাদনা করুন",
      "select_profile_photo": "প্রোফাইল ফটো নির্বাচন করুন",
      "camera": "ক্যামেরা",
      "gallery": "গ্যালারি",
      "update": "আপডেট",
      "enter_your_height": "আপনার উচ্চতা লিখুন",
      "enter_your_weight": "আপনার ওজন লিখুন",

      "failed_to_pick_image": "ছবি নির্বাচন করতে ব্যর্থ হয়েছে",
      "welcome_back": "ফিরে আসার জন্য স্বাগতম,",
      "3d_baby_visualization": "৩ডি বেবি ভিজুয়ালাইজেশন",
      "baby_size_visualization": "বেবি সাইজ ভিজুয়ালাইজেশন",
      "message": "বার্তা",
      "comming_soon": "শীঘ্রই আসছে",
      "todays_tips": "আজকের টিপস",
      "see_all": "সব দেখুন",

      "baby_growth_tracker": "বেবি গ্রোথ ট্র্যাকার",
      "day": "দিন",
      "baby_currently_size": "বেবি বর্তমানে নারকেলের আকারের",
      "baby_weight": "বেবির ওজন",
      "delivery_date": "প্রসব তারিখ",
      "conception_information": "গর্ভধারণ তথ্য",
      "trying_to_conceive_since": "গর্ভধারণের চেষ্টা করছেন",
      "select_conceive_date": "তারিখ নির্বাচন করুন",
      "any_existing_health_conditions":
          "কোনো বিদ্যমান স্বাস্থ্য সমস্যা? (ঐচ্ছিক)",
      "enter_health_conditions": "স্বাস্থ্য সমস্যা থাকলে লিখুন",
      "full_name_required": "পুরো নাম প্রয়োজন",
      "full_name_min_length": "পুরো নাম কমপক্ষে ২ অক্ষরের হতে হবে",
      "date_of_birth_required": "জন্ম তারিখ প্রয়োজন",
      "must_be_18_years": "কমপক্ষে ১৮ বছর বয়সী হতে হবে",
      "invalid_date_of_birth": "দয়া করে একটি বৈধ জন্ম তারিখ লিখুন",
      "select_gender_required": "দয়া করে লিঙ্গ নির্বাচন করুন",

      "conceive_date_before_birth":
          "গর্ভধারণের তারিখ জন্ম তারিখের আগে হতে পারে না",
      "location_required": "লোকেশন প্রয়োজন",

      "invalid_email": "দয়া করে একটি বৈধ ইমেইল লিখুন",
      "height_required": "উচ্চতা প্রয়োজন",
      "invalid_height": "দয়া করে একটি বৈধ উচ্চতা লিখুন (১-৩০০ সেমি)",
      "weight_required": "ওজন প্রয়োজন",
      "invalid_weight": "দয়া করে একটি বৈধ ওজন লিখুন (১-৫০০ কেজি)",

      // Success/Error messages in Bangla
      "profile_saved_successfully": "প্রোফাইল সফলভাবে সংরক্ষণ করা হয়েছে!",
      "profile_save_failed": "প্রোফাইল সংরক্ষণ করতে ব্যর্থ হয়েছে",

      // Image picker messages in Bangla
      "period_days": "মাসিকের দিন",
      "menstruation": "মাসিক",
      "ovulation": "ডিম্বস্ফোটন",
      "proliferative": "প্রলিফারেটিভ",
      "secretory": "সিক্রেটরি",

      "period_tracker": "পিরিয়ড ট্র্যাকার",

      "end_cycle": "চক্র শেষ করুন",
      "ovulation_time": "ডিম্বস্ফোটনের সময়",
      "period_start": "পিরিয়ড শুরু",
      "new_cycle": "নতুন চক্র শুরু করুন",

      "sneho_expert_tips": "স্নেহ বিশেষজ্ঞ টিপস",
      "day_wish_tips": "দিন অনুযায়ী টিপস",
      "no_tips_available_for_day": "দিনের জন্য কোন টিপস উপলব্ধ নেই",

      // Doctor List Screen
      "sneho_doctors": "স্নেহ ডাক্তারগণ",
      "i_am_looking_for": "আমি খুঁজছি",
      "doctors_available": "@count জন ডাক্তার উপলব্ধ",
      "gynecologist": "স্ত্রীরোগ বিশেষজ্ঞ",
      "year_exp": "বছরের অভিজ্ঞতা",
      "available_now": "এখন উপলব্ধ",
      "offline_now": "এখন অফলাইন",
      "video_call": "ভিডিও কল",
      "consultation_fee": "পরামর্শ ফি",
      "instant_appointment": "অবিলম্বে অ্যাপয়েন্টমেন্ট",

      // Doctor Details Screen
      "doctor_profile": "ডাক্তারের প্রোফাইল",
      "experience": "অভিজ্ঞতা",
      "patients": "রোগী",
      "biography": "জীবনী",
      "what_people_say": "লোকেরা যা বলে",
      "review_on": "-এ",

      // Doctor Payment Screen
      "overview": "সংক্ষিপ্ত বিবরণ",
      "patient_information": "রোগীর তথ্য",
      "mobile_number": "মোবাইল নম্বর",
      "patient_name": "রোগীর নাম",
      "add_prescription_report": "প্রেসক্রিপশন / রিপোর্ট যোগ করুন",
      "consultation_type": "পরামর্শের ধরন",
      "talk_to_doctor_video_call": "ভিডিও কলে ডাক্তারের সাথে কথা বলুন",
      "book_appointment": "অ্যাপয়েন্টমেন্ট বুক করুন",
      "payment_details": "পেমেন্টের বিবরণ",
      "promo_code": "প্রোমো কোড",
      "apply": "প্রয়োগ করুন",
      "vat_5_percent": "ভ্যাট (৫%)",
      "platform_fee": "প্ল্যাটফর্ম ফি",
      "total_amount": "সর্বমোট পরিমাণ",
      "payment_now": "এখন পেমেন্ট করুন",

      // Tools Screen
      "sneho_tools": "স্নেহ টুলস",
      "doctor_prescription": "ডাক্তারের প্রেসক্রিপশন",
      "doctor_appointment": "ডাক্তারের অ্যাপয়েন্টমেন্ট",

      // Doctor Appointment/Prescription Tool
      "upcoming": "আসন্ন",
      "previous": "পূর্ববর্তী",
      "view_appointment": "অ্যাপয়েন্টমেন্ট দেখুন",
      "view_prescription": "প্রেসক্রিপশন দেখুন",

      // Profile Screen
      "gender": "লিঙ্গ",
      "select_gender": "লিঙ্গ নির্বাচন করুন",
      "male": "পুরুষ",
      "female": "মহিলা",
      "other": "অন্যান্য",
      "email_address": "ইমেল ঠিকানা",
      "enter_your_location": "আপনার অবস্থান লিখুন",
      "update_profile": "প্রোফাইল আপডেট করুন",
      "remove_image": "ছবি সরান",
      "profile_updated_successfully": "প্রোফাইল সফলভাবে আপডেট করা হয়েছে!",
      "profile_update_failed": "প্রোফাইল আপডেট করতে ব্যর্থ হয়েছে",
      "loading_profile_data": "প্রোফাইল ডেটা লোড হচ্ছে...",
      "account_login": "অ্যাকাউন্ট লগইন",
      "login_description":
          "স্নেহ অ্যাপে ডাক্তার অ্যাপয়েন্টমেন্ট এবং মেডিকেল কনসালটেশন যাত্রা শুরু করুন",
      "phone_number": "ফোন নম্বর",
      "enter_phone_number": "ফোন নম্বর লিখুন",
      "enter_password": "পাসওয়ার্ড লিখুন",
      "remember_me": "আমাকে মনে রাখুন",
      "create_account": "অ্যাকাউন্ট তৈরি করুন",
      "register_description":
          "রেজিস্ট্রেশন করুন এবং স্নেহ অ্যাপে ডাক্তার অ্যাপয়েন্টমেন্ট ও মেডিকেল কনসালটেশন শুরু করুন",
      "name": "নাম",
      "enter_name": "নাম লিখুন",
      "sign_in": "সাইন ইন",

      "aci_pure_products": "এসিআই পিওর প্রোডাক্টস",
      "health_wellness": "স্বাস্থ্য ও সুস্থতা",
      "popular_specialists": "জনপ্রিয় বিশেষজ্ঞরা",
      "view_all": "সব দেখুন",
      "view_all_specialists": "সব বিশেষজ্ঞ দেখুন",
      "medicine_specialist": "মেডিসিন বিশেষজ্ঞ",
      "dermatology": "চর্মরোগবিদ্যা",
      "years": "বছর",

      "find_doctors_by_department": "বিভাগ অনুযায়ী ডাক্তার খুঁজুন",
      "view_all_departments": "সব বিভাগ দেখুন",
      "select_clinical_areas":
          "ডাক্তার খুঁজতে ৩০+ ক্লিনিকাল এলাকা থেকে নির্বাচন করুন",
      "instant_video_consultation": "তাৎক্ষণিক ভিডিও পরামর্শ পান",
      "consultation_24_7": "মাত্র ১০ মিনিটের মধ্যে ২৪/৭ পরামর্শ পান",
      "experienced_mbbs_doctor": "অভিজ্ঞ এমবিবিএস ডাক্তার",
      "experienced_child_doctor": "অভিজ্ঞ শিশু বিশেষজ্ঞ",
      "experienced_female_gyne": "অভিজ্ঞ মহিলা গাইনী",
      "treat_dengue_fever": "ডেঙ্গু জ্বরের চিকিৎসা",
      "view_details": "বিস্তারিত দেখুন >",

      // Department names in Bangla
      "general_physician": "জেনারেল ফিজিশিয়ান",
      "pediatrics": "শিশুরোগ",
      "gynae_ops": "গাইনী ও অপারেশন",
      "internal_medicine": "অভ্যন্তরীণ মেডিসিন",
      "endocrinology": "এন্ডোক্রিনোলজি",
      "neurology": "নিউরোলজি",
      "gastroenterology": "গ্যাস্ট্রোএন্টারোলজি",
      "cardiology": "কার্ডিওলজি",
      "urology": "ইউরোলজি",
      "nutrition_food_science": "পুষ্টি ও খাদ্য বিজ্ঞান",
      "dentistry": "দন্তচিকিৎসা",
      "setup_your_profile": "আপনার প্রোফাইল সেটআপ করুন",
      "create_medical_profile": "আপনার মেডিকেল কনসালটেশন প্রোফাইল তৈরি করুন",
      "medical_information": "মেডিকেল তথ্য",
      "consultation_purpose": "পরামর্শের উদ্দেশ্য / মেডিকেল উদ্বেগ (সংক্ষিপ্ত)",

      "month": "মাস",
      "baby_age": "বেবির বয়স",
      "days_left_to_turn_two": "বাচ্চার ২ বছর হতে ৩০৪ দিন বাকি",
      "child_information": "শিশুর তথ্য",
      "childs_name": "শিশুর নাম",
      "enter_your_childs_name": "আপনার শিশুর নাম লিখুন",
      "childs_birth_date": "শিশুর জন্ম তারিখ",
      "select_childs_birth_date": "শিশুর জন্ম তারিখ নির্বাচন করুন",
      "childs_gender": "শিশুর লিঙ্গ",
      "childs_blood_group": "শিশুর ব্লাড গ্রুপ",
      "number_of_children": "শিশুর সংখ্যা",
      "enter_number_of_children": "শিশুর সংখ্যা লিখুন",
      "child_name_required": "শিশুর নাম প্রয়োজন",
      "child_birth_date_required": "শিশুর জন্ম তারিখ প্রয়োজন",
      "select_blood_group_required": "দয়া করে শিশুর ব্লাড গ্রুপ নির্বাচন করুন",
      "number_of_children_required": "শিশুর সংখ্যা প্রয়োজন",
      "min_children_required": "শিশুর সংখ্যা কমপক্ষে ১ হতে হবে",
      "valid_number_required": "দয়া করে একটি বৈধ সংখ্যা লিখুন",
      "valid_height_required": "দয়া করে একটি বৈধ উচ্চতা লিখুন",
      "valid_weight_required": "দয়া করে একটি বৈধ ওজন লিখুন",
      "birthday": "জন্মদিন",
      "describe_medical_concern":
          "আপনার মেডিকেল উদ্বেগ বা পরামর্শের কারণ বর্ণনা করুন",
      "terms_confirmation":
          "অগ্রসর হওয়ার মাধ্যমে, আপনি স্বীকার করছেন যে আপনার বয়স ১৮ বছর বা তার বেশি এবং আপনি আমাদের সেবার শর্তাবলী ও গোপনীয়তা নীতি মেনে চলতে সম্মত আছেন।",

      "Health_Support": "স্বাস্থ্য সহায়তা",
      "Emotional_Wellbeing": "মানসিক সুস্থতা",
      "Healthy_Lifestyle": "সুস্থ জীবনধারা",
      "Nutrition_Guide": "পুষ্টি নির্দেশনা",
      "Fertility_Awareness": "ফার্টিলিটি সচেতনতা",
      'ovulating_now': 'ডিম্বস্ফোটন চলছে',
      'next_ovulation': 'পরবর্তী ডিম্বস্ফোটন',
      "Parents_Self_Care": "প্যারেন্টদের সেলফ কেয়ার",
      "Childhood_Diseases_Care": "শিশুর বিষয় সেলফ কেয়ার",
      "Sleep_Routine": "স্নাতক করুন",
      "Special_Baby_Care": "বিশেষ শিশুর সেলফ কেয়ার",
      "patient_problem": "প্রয়োজনীয় সমস্যা",
      "say_something": "কিছু বলুন",
      "please_enter_your_problem": "আপনার প্রয়োজনীয় সমস্যা লিখুন",
      "describe_your_problem_in_at_least_5_characters":
          "আপনার প্রয়োজনীয় সমস্যা ৫ অক্ষরের কমে বর্ণনা করুন",
      "Food_Nutrition": "খাদ্য ও পুষ্টি",
      "Mothers_Health": "মায়ের স্বাস্থ্য",
      "Mothers_Risks": "মায়ের ঝুঁকি",
      "Pregnancy_Mother_Care": "গর্ভাবস্থার যত্ন",
      "Mothers_Beauty": "মায়ের সৌন্দর্য",
      "no_tips_available": "কোনো টিপস উপলব্ধ নেই",
      "how_can_we_help": "আমরা কিভাবে আপনাকে সাহায্য করতে পারি?",
      "support_message":
          "আপনার যেকোনো প্রশ্ন বা উদ্বেগে সহায়তা করতে আমরা এখানে আছি। আমাদের সাথে যোগাযোগের জন্য আপনার পছন্দের উপায় বেছে নিন।",
      "email_support": "ইমেইল সহায়তা",
      "phone_support": "ফোন সহায়তা",
      "whatsapp_support": "হোয়াটসঅ্যাপ সহায়তা",
      "chat_with_us": "হোয়াটসঅ্যাপে আমাদের সাথে চ্যাট করুন",
      "faq": "সাধারণ প্রশ্নাবলী",
      "office_hours": "অফিস সময়",
      "saturday_thursday": "শনিবার - বৃহস্পতিবার",
      "friday_closed": "শুক্রবার: বন্ধ",
      "how_to_update_profile": "আমি কিভাবে আমার প্রোফাইল আপডেট করব?",
      "profile_update_answer":
          "আপনার প্রোফাইলে যান, এডিট আইকনে ট্যাপ করুন, পরিবর্তন করুন এবং সংরক্ষণ করুন। আপনার তথ্য অবিলম্বে আপডেট হবে।",
      "how_to_track_pregnancy": "আমি কিভাবে আমার গর্ভাবস্থা ট্র্যাক করব?",
      "pregnancy_track_answer":
          "অ্যাপটি আপনার এলএমপি তারিখের উপর ভিত্তি করে স্বয়ংক্রিয়ভাবে আপনার গর্ভাবস্থা ট্র্যাক করে। হোম স্ক্রিনে আপনার অগ্রগতি দেখুন।",
      "app_support_languages": "অ্যাপটি কোন ভাষা সমর্থন করে?",
      "language_support_answer":
          "স্নেহ বর্তমানে ইংরেজি এবং বাংলা সমর্থন করে। আপনি প্রোফাইল স্ক্রিন থেকে ভাষা পরিবর্তন করতে পারেন।",

      // Privacy Policy Screen (Bengali)
      "last_updated": "সর্বশেষ আপডেট",
      "introduction": "ভূমিকা",
      "information_we_collect": "আমরা যে তথ্য সংগ্রহ করি",
      "how_we_use_info": "আমরা কিভাবে আপনার তথ্য ব্যবহার করি",
      "data_sharing": "ডেটা শেয়ারিং এবং প্রকাশ",
      "data_security": "ডেটা নিরাপত্তা",
      "your_rights": "আপনার অধিকার",
      "data_retention": "ডেটা ধারণ",
      "childrens_privacy": "শিশুদের গোপনীয়তা",
      "international_transfers": "আন্তর্জাতিক ডেটা স্থানান্তর",
      "policy_changes": "এই নীতিতে পরিবর্তন",

      // About Sneho Screen (Bengali)
      "version": "সংস্করণ",
      "sneho_tagline":
          "গর্ভাবস্থা এবং প্যারেন্টিং এর জন্য আপনার বিশ্বস্ত সঙ্গী",
      "our_mission": "আমাদের লক্ষ্য",
      "mission_description":
          "স্নেহ মা এবং পরিবারকে নির্ভরযোগ্য স্বাস্থ্য তথ্য, বিশেষজ্ঞ নির্দেশনা এবং গর্ভাবস্থা ও প্যারেন্টিং যাত্রা জুড়ে সহানুভূতিশীল সহায়তা প্রদানের জন্য নিবেদিত। আমরা বিশ্বাস করি প্রতিটি মা মানসম্পন্ন স্বাস্থ্যসেবা এবং ব্যক্তিগত যত্ন পাওয়ার যোগ্য।",
      "what_we_offer": "আমরা যা অফার করি",
      "pregnancy_tracking": "গর্ভাবস্থা ট্র্যাকিং",
      "pregnancy_tracking_desc":
          "ব্যক্তিগত অন্তর্দৃষ্টি সহ সপ্তাহে সপ্তাহে আপনার গর্ভাবস্থার যাত্রা পর্যবেক্ষণ করুন",
      "health_tips": "স্বাস্থ্য টিপস এবং নির্দেশনা",
      "health_tips_desc":
          "আপনার গর্ভাবস্থার পর্যায়ে উপযুক্ত দৈনিক বিশেষজ্ঞ টিপস",
      "expert_support": "বিশেষজ্ঞ সহায়তা",
      "expert_support_desc":
          "যোগ্য ডাক্তার এবং স্বাস্থ্যসেবা পেশাদারদের সাথে সংযোগ করুন",
      "multilingual": "বহুভাষিক সহায়তা",
      "multilingual_desc":
          "আরও ভাল অ্যাক্সেসযোগ্যতার জন্য ইংরেজি এবং বাংলায় উপলব্ধ",
      "our_team": "আমাদের দল",
      "team_description":
          "স্নেহ একটি উৎসাহী দলের দ্বারা নির্মিত যা স্বাস্থ্যসেবা পেশাদার, ডেভেলপার এবং পিতামাতা নিয়ে গঠিত যারা গর্ভাবস্থা এবং প্যারেন্টিংয়ের চ্যালেঞ্জগুলি বোঝেন। আমরা আপনাকে সর্বোত্তম সম্ভাব্য অভিজ্ঞতা প্রদান করতে নিরলসভাবে কাজ করি।",
      "connect_with_us": "আমাদের সাথে সংযুক্ত হন",
      "all_rights_reserved": "সর্বস্বত্ব সংরক্ষিত",
      "this_month_tips": "এই মাসের টিপস",
      "baby_vaccine": "বেবি ভ্যাকসিন",
    },
  };
}
